### ISSUE TITLE
Add a test that runs all of the examples

### ISSUE THREAD

**Issue by samuelhwilliams** [pallets-eco/flask-admin#2470]
A number of our example apps have had typos and small bugs in them, preventing them from actually running.

We should add a test/some tests that run all of the examples to make sure that they actually work (with their associated requirements files).

A single tox environment to run all of the examples would probably be good. In the first instance, just testing that the apps all run and a page is available on `localhost:5000/admin` is probably good enough. We could firm them up from there.

This test should dynamically collect all packages in the `examples` directory so that if any new examples are added, they are tested without having to change any config files anywhere (ie to explicitly add the new example to the test suite).

**Comment by hasansezertasan** [comment]
Progress:

- [ ] auth
- [ ] auth_flask_login
- [ ] azure_blob_storage
- [ ] babel
- [ ] bootstrap4
- [ ] csp_nonce
- [ ] custom_layout
- [ ] datetime_timezone
- [ ] files
- [ ] forms_files_images
- [ ] geo_alchemy
- [ ] host_matching
- [ ] methodview
- [ ] mongoengine
- [ ] multiple_admin_instances
- [ ] peewee_simple
- [ ] pymongo_simple
- [ ] rediscli
- [ ] s3
- [ ] simple
- [ ] sqla
- [ ] sqla_association_proxy
- [ ] sqla_column_editable
- [ ] sqla_custom_inline_forms

**Comment by hasansezertasan** [comment]
Hi! I'd like to propose implementing this as a GitHub Actions workflow. The idea is:

1. A first job dynamically discovers all directories under `examples/` and outputs them as a matrix.
2. A second job runs each example in parallel — installs its requirements, starts `main.py`, and verifies that `/admin` returns a 200 response.

New examples would be picked up automatically without any config changes. Here's a rough sketch:

```yaml
name: Smoke Test Examples

on:
  push:
    branches:
      - master
      - "*.x"
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - "*.rst"
  schedule:
    - cron: "0 3 * * 1"

jobs:
  discover-examples:
    name: Discover examples
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.find.outputs.matrix }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Find all examples
        id: find
        run: |
          EXAMPLES=$(find examples -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "matrix=${EXAMPLES}" >> $GITHUB_OUTPUT

  smoke-test:
    name: "Smoke: ${{ matrix.example }}"
    needs: discover-examples
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJson(needs.discover-examples.outputs.matrix) }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: astral-sh/setup-uv@5a095e7a2014a4212f075830d4f7277575a9d098 # v7.3.1
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: |
            **/uv.lock
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: pyproject.toml

      - name: Install dependencies
        working-directory: examples/${{ matrix.example }}
        run: uv sync

      - name: Start app and smoke test
        working-directory: examples/${{ matrix.example }}
        run: |
          uv run main.py &
          APP_PID=$!

          for i in $(seq 1 30); do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/admin | grep -q "200"; then
              echo "App is up!"
              kill $APP_PID
              exit 0
            fi
            sleep 1
          done

          echo "App failed to respond with 200 within 30 seconds"
          kill $APP_PID 2>/dev/null || true
          exit 1
```

This keeps the test suite untouched while still catching broken examples in CI. Examples using testcontainers should work since the GitHub Actions runners have Docker available. Would this approach work, or would you prefer it integrated into tox/pytest?
